# Base image con Node 20 y Debian Bullseye
FROM node:20-bullseye

# Set working directory
WORKDIR /usr/src/app

# Installing dependencies
RUN apt-get update && apt-get install -y \
    curl \
    libnss3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libgbm1 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libasound2 \
    libxshmfence1 \
    libwayland-client0 \
    libwayland-cursor0 \
    libwayland-egl1 \
    libegl1 \
    libdbus-1-3 \
    libdrm2 \
    libexpat1 \
    libffi7 \
    libfontconfig1 \
    libfreetype6 \
    libglib2.0-0 \
    libgtk-3-0 \
    libjpeg62-turbo \
    liblzma5 \
    libnspr4 \
    libnss3 \
    libx11-6 \
    libxcb1 \
    libxext6 \
    libxfixes3 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    xdg-utils \
    --no-install-recommends && rm -rf /var/lib/apt/lists/*

# copy package json for faster installation
COPY package*.json ./

# Installing project dependencies 
RUN npm install

# Installing browsers
RUN npx playwright install --with-deps

# This copy all the test and structure
COPY . .

# Setting up environment url to use the one inside the container
ENV BASE_URL=http://demo-app:3100

# Entrypoint allows the ability to pass arguments to test execution
ENTRYPOINT ["npx", "playwright", "test"]
